#!/usr/bin/env bash
# This file was autonomously generated by an AI agent.
set -euo pipefail

case "${1:-build}" in
    setup|build)
        : "${MIXXX_SRC:?Run this script through mise}"
        : "${MIXXX_APPIMAGE_CONTAINER:?Run this script through mise}"
        if [ "${1:-build}" = setup ] || ! podman image exists "$MIXXX_APPIMAGE_CONTAINER"; then
            podman build \
                --file "$MIXXX_SRC/tools/appimage.Containerfile" \
                --tag "$MIXXX_APPIMAGE_CONTAINER" \
                "$MIXXX_SRC/tools"
        fi
        if [ "${1:-build}" = setup ]; then
            exit 0
        fi

        : "${MIXXX_BUILD_APPIMAGE:?Run this script through mise}"
        : "${BUILDENV_BASEPATH:?Run this script through mise}"
        : "${CCACHE_DIR:?Run this script through mise}"
        mkdir -p "$MIXXX_BUILD_APPIMAGE" "$BUILDENV_BASEPATH" "$CCACHE_DIR/ubuntu22"
        exec podman run --rm --userns=keep-id --security-opt label=disable \
            --volume "$MIXXX_SRC:/workspace:ro" \
            --volume "$MIXXX_BUILD_APPIMAGE:/build:rw" \
            --volume "$BUILDENV_BASEPATH:/buildenv:rw" \
            --volume "$CCACHE_DIR/ubuntu22:/ccache:rw" \
            --env HOME=/tmp \
            --env BUILDENV_BASEPATH=/buildenv \
            --env CCACHE_DIR=/ccache \
            --env CMAKE_BUILD_PARALLEL_LEVEL="${CMAKE_BUILD_PARALLEL_LEVEL:-4}" \
            "$MIXXX_APPIMAGE_CONTAINER" \
            bash /workspace/tools/appimage_container.sh inside
        ;;
    inside)
        set +u
        source /workspace/tools/appimage_buildenv.sh env
        set -u
        ccache --set-config=max_size=16G
        cmake -S /workspace -B /build -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE="$MIXXX_VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_BUILD_TYPE=Release \
            -DCPACK_GENERATOR=AppImage \
            -DQT6=ON -DQML=ON \
            -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DINSTALL_USER_UDEV_RULES=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="-Wl,--allow-shlib-undefined"
        cmake --build /build
        cd /build
        cpack -G AppImage -D CPACK_MIXXX_APPIMAGE_FILE_NAME=mixxx
        ;;
    *)
        exit 2
        ;;
esac
# End of text autonomously generated by an AI agent.
