# This file was autonomously generated by an AI agent.
FROM docker.io/library/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl git ninja-build python3-pip sudo \
    && python3 -m pip install --no-cache-dir cmake==4.2.0

COPY appimage_buildenv.sh /opt/mixxx/tools/appimage_buildenv.sh
RUN bash -e -c 'source /opt/mixxx/tools/appimage_buildenv.sh setup' \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends libpipewire-0.3-0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV APPIMAGE_EXTRACT_AND_RUN=1
WORKDIR /workspace
# End of text autonomously generated by an AI agent.
