#!/usr/bin/env python3
# This file was autonomously generated by an AI agent.
import argparse
import re
import shutil
import subprocess
from pathlib import Path


HOST_LIBRARIES = re.compile(
    r"^(?:ld-linux.*|lib(?:c|m|dl|pthread|rt|resolv|util|nss_.*|mvec|anl|"
    r"thread_db|BrokenLocale|stdc\+\+|gcc_s|GL|GLESv[12]|EGL|GLX|OpenGL|"
    r"GLdispatch|"
    r"drm.*|glapi|gbm|vulkan|wayland-.*|X11|X11-xcb|xcb.*|asound|jack|"
    r"pipewire.*)\.so(?:\..*)?)$"
)


def is_elf(path):
    if not path.is_file():
        return False
    with path.open("rb") as stream:
        header = stream.read(18)
    if len(header) != 18 or header[:4] != b"\x7fELF":
        return False
    byte_order = "little" if header[5] == 1 else "big"
    return int.from_bytes(header[16:18], byte_order) in (2, 3)


def dependencies(path):
    result = subprocess.run(
        ["ldd", str(path)], check=True, capture_output=True, text=True
    )
    found = {}
    for line in result.stdout.splitlines():
        if "=> not found" in line:
            raise RuntimeError(
                f"Missing runtime dependency of {path}: {line.strip()}"
            )
        match = re.match(r"\s*(\S+) => (/.*?) \(", line)
        if match:
            found[Path(match[1]).name] = Path(match[2])
    return found


def bundle(root, qt_plugins, qt_qml):
    library_dir = root / "lib"
    library_dir.mkdir(exist_ok=True)
    for source, destination in (
        (qt_plugins, root / "qt/plugins"),
        (qt_qml, root / "qt/qml"),
    ):
        if not source.is_dir():
            raise RuntimeError(
                f"Qt runtime directory does not exist: {source}"
            )
        shutil.copytree(
            source,
            destination,
            ignore=shutil.ignore_patterns("*.a", "*.o", "*.prl", "objects-*"),
        )

    binaries = [path for path in root.rglob("*") if is_elf(path)]
    libraries = {}
    for binary in binaries:
        for name, source in dependencies(binary).items():
            if HOST_LIBRARIES.fullmatch(name):
                continue
            previous = libraries.get(name)
            if previous is not None and previous.resolve() != source.resolve():
                raise RuntimeError(
                    f"Conflicting libraries named {name}: {previous}, {source}"
                )
            libraries[name] = source

    for name, source in sorted(libraries.items()):
        destination = library_dir / name
        shutil.copy2(source.resolve(), destination)
        subprocess.run(
            ["strip", "--strip-unneeded", str(destination)], check=True
        )

    for binary in binaries:
        subprocess.run(["strip", "--strip-unneeded", str(binary)], check=True)

    (root / "bin/qt.conf").write_text(
        "[Paths]\nPrefix=..\nPlugins=qt/plugins\nQmlImports=qt/qml\n",
        encoding="utf-8",
    )
    print(
        f"Bundled {len(libraries)} runtime libraries "
        "and Qt plugins/QML modules"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    parser.add_argument(
        "--qt-plugins", type=Path, default=Path("/usr/lib64/qt6/plugins")
    )
    parser.add_argument(
        "--qt-qml", type=Path, default=Path("/usr/lib64/qt6/qml")
    )
    args = parser.parse_args()
    bundle(args.root, args.qt_plugins, args.qt_qml)


if __name__ == "__main__":
    main()
# End of text autonomously generated by an AI agent.
