#!/usr/bin/env bash
# This file was autonomously generated by an AI agent.
set -euo pipefail

case "${1:-build}" in
    setup|build)
        : "${MIXXX_SRC:?Run this script through mise}"
        : "${MIXXX_FEDORA_RELEASE:=44}"
        : "${MIXXX_FEDORA_CONTAINER:=localhost/mixxx-fedora:${MIXXX_FEDORA_RELEASE}}"
        if [[ "$(uname -m)" != x86_64 ]]; then
            echo "This Fedora archive build requires an x86_64 host." >&2
            exit 1
        fi
        if [[ "${1:-build}" == setup ]] || ! podman image exists "$MIXXX_FEDORA_CONTAINER"; then
            podman build \
                --build-arg "FEDORA_RELEASE=$MIXXX_FEDORA_RELEASE" \
                --file "$MIXXX_SRC/tools/fedora.Containerfile" \
                --tag "$MIXXX_FEDORA_CONTAINER" \
                "$MIXXX_SRC/tools"
        fi
        if [[ "${1:-build}" == setup ]]; then
            exit 0
        fi
        : "${MIXXX_BUILD_FEDORA:=$MIXXX_SRC/build-fedora$MIXXX_FEDORA_RELEASE}"
        : "${CCACHE_DIR:?Run this script through mise}"
        mkdir -p "$MIXXX_BUILD_FEDORA" "$CCACHE_DIR/fedora$MIXXX_FEDORA_RELEASE"
        exec podman run --rm --userns=keep-id --security-opt label=disable \
            --volume "$MIXXX_SRC:/workspace:ro" \
            --volume "$MIXXX_BUILD_FEDORA:/build:rw" \
            --volume "$CCACHE_DIR/fedora$MIXXX_FEDORA_RELEASE:/ccache:rw" \
            --env CCACHE_DIR=/ccache \
            --env "MIXXX_FEDORA_RELEASE=$MIXXX_FEDORA_RELEASE" \
            --env CMAKE_BUILD_PARALLEL_LEVEL="${CMAKE_BUILD_PARALLEL_LEVEL:-4}" \
            "$MIXXX_FEDORA_CONTAINER" \
            bash /workspace/tools/fedora_container.sh inside
        ;;
    inside)
        ccache --set-config=max_size=16G
        cmake -S /workspace -B /build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DQT6=ON -DQML=ON \
            -DPIPEWIRE=ON \
            -DMIXXX_APPIMAGE=OFF \
            -DBUILD_TESTING=OFF -DBUILD_BENCH=OFF \
            -DCMAKE_INSTALL_PREFIX=/opt/mixxx \
            -DCMAKE_INSTALL_LIBDIR=lib \
            '-DCMAKE_INSTALL_RPATH=$ORIGIN/../lib' \
            -DINSTALL_USER_UDEV_RULES=OFF
        cmake --build /build --target mixxx
        staging_dir="$(mktemp -d /build/fedora-stage.XXXXXX)"
        trap 'rm -rf -- "$staging_dir"' EXIT
        cmake --install /build --prefix "$staging_dir/mixxx"
        python3 /workspace/tools/bundle_fedora.py "$staging_dir/mixxx"
        cp /workspace/packaging/fedora/run-mixxx "$staging_dir/mixxx/run-mixxx"
        chmod +x "$staging_dir/mixxx/run-mixxx"
        archive="/build/mixxx-fedora${MIXXX_FEDORA_RELEASE}-x86_64.tgz"
        tar -czf "$staging_dir/package.tgz" -C "$staging_dir" mixxx
        mv -f -- "$staging_dir/package.tgz" "$archive"
        echo "Created $archive"
        ;;
    *)
        echo "Usage: $0 [setup|build]" >&2
        exit 2
        ;;
esac
# End of text autonomously generated by an AI agent.
