# This file was autonomously generated by an AI agent.
ARG FEDORA_RELEASE=44
FROM quay.io/fedora/fedora:${FEDORA_RELEASE}

RUN dnf install -y ca-certificates ccache cmake dnf5-plugins gcc-c++ git \
        gzip ninja-build patchelf python3 tar \
    && dnf install -y "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" \
    && dnf builddep -y mixxx \
    && dnf install -y qt6-qt5compat-devel qt6-qtbase-devel qt6-qtbase-private-devel \
        qt6-qtdeclarative-devel qt6-qtmultimedia-devel qt6-qtshadertools-devel \
        qt6-qtsvg-devel qt6-qtwayland-devel qtkeychain-qt6-devel \
    && dnf clean all

RUN dnf install -y pipewire-devel && dnf clean all

WORKDIR /workspace
# End of text autonomously generated by an AI agent.
